fill in missing changelog entries based on pull request numbers in commit history
spacetelescope/stcal pull request #101
Opened 2022-06-16 16:24 UTC by zacharyburnett

I used the following script to find discrepancies between the 
```python
import re
import sys
from pathlib import Path

from git import Repo

changelog_pull_request_pattern = re.compile('\[(#\d+)\]')
commit_pull_request_pattern = re.compile('#\d+')

repo = Repo('.')

commit_messages = '\n'.join([commit.message for commit in repo.iter_commits()])
commit_pull_requests = re.findall(commit_pull_request_pattern, commit_messages)

with open(Path(repo.working_dir) / 'CHANGES.rst') as change_log:
    changelog_pull_requests = re.findall(changelog_pull_request_pattern, change_log.read())

for pull_request in commit_pull_requests:
    if pull_request not in changelog_pull_requests:
        print(f'pull request {pull_request} not in changelog', file=sys.stderr)
```

2022-06-16 16:25 UTC, zacharyburnett commented
the remaining pull requests seem to be trivial changes:
```
pull request #93 not in changelog
pull request #88 not in changelog
pull request #86 not in changelog
pull request #80 not in changelog
pull request #77 not in changelog
pull request #73 not in changelog
pull request #62 not in changelog
pull request #56 not in changelog
pull request #53 not in changelog
pull request #46 not in changelog
pull request #46 not in changelog
pull request #48 not in changelog
pull request #29 not in changelog
pull request #28 not in changelog
pull request #15 not in changelog
pull request #11 not in changelog
pull request #9 not in changelog
pull request #8 not in changelog
pull request #1 not in changelog
```

2022-06-16 17:20 UTC, nden requested changes

2022-06-16 17:20 UTC, nden commented on CHANGES.rst
> +- Use new ``publish-to-pypi.yml`` to build & publish wheels [#69]
I would remove this one as not interesting to users

2022-06-16 17:20 UTC, nden commented on CHANGES.rst
> +- Add pypi publish workflow and fix jwst CI [#21]
remove this one

2022-06-16 17:56 UTC, zacharyburnett commented
do you think there should also be an `Other` section for changes to documentation or build configuration?

2022-06-17 12:29 UTC, zacharyburnett commented on .github/pull_request_template.md
> +- [ ] added relevant label(s)
I copied the pull request template from `jwst` and modified it to explicitly ask to update `CHANGES.txt` in the relevant section

2022-06-21 16:54 UTC, zacharyburnett commented on .github/pull_request_template.md
> +
done in 18a9ad1

2022-06-21 16:56 UTC, zacharyburnett commented
Posting the script here so we can use it later if it is needed:
```python
import re
import sys
from pathlib import Path

from git import Repo

changelog_pull_request_pattern = re.compile('\[(#\d+)\]')
commit_pull_request_pattern = re.compile('#\d+')

repository = Repo('.')
changelog_filename = Path(repository.working_dir) / 'CHANGES.rst'

commit_messages = '\n'.join([commit.message for commit in repository.iter_commits(rev=None)])
commit_pull_requests = re.findall(commit_pull_request_pattern, commit_messages)

print(f'found {len(commit_pull_requests)} pull requests in main branch')

with open(changelog_filename) as change_log:
    changelog_pull_requests = re.findall(changelog_pull_request_pattern, change_log.read())

print(f'found {len(changelog_pull_requests)} pull requests in "{changelog_filename.name}"')

missing_commit_pull_requests = []
for pull_request in commit_pull_requests:
    if pull_request not in changelog_pull_requests:
        missing_commit_pull_requests.append(pull_request)
if len(missing_commit_pull_requests) > 0:
    print(
        f'found {len(missing_commit_pull_requests)} pull requests from "{changelog_filename.name}" '
        f'that are not in commit history: \n'
        f'{" ".join(missing_commit_pull_requests)}',
        file=sys.stderr,
    )

missing_changelog_pull_requests = []
for pull_request in changelog_pull_requests:
    if pull_request not in commit_pull_requests:
        missing_changelog_pull_requests.append(pull_request)
if len(missing_changelog_pull_requests) > 0:
    print(
        f'found {len(missing_changelog_pull_requests)} pull requests from commit history '
        f'that are not in "{changelog_filename.name}": \n'
        f'{" ".join(missing_changelog_pull_requests)}',
        file=sys.stderr,
    )
```

2022-06-21 17:34 UTC, merged