test against pre-built binaries of `astropy`, `scipy`, and `numpy`
spacetelescope/stcal pull request #166
Opened 2023-05-09 14:18 UTC by zacharyburnett

Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)

test against `pre` wheels of `astropy`, `scipy`, and `numpy` to ensure incoming issues are resolved

**Checklist**
- [ ] ~added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)~
- [ ] updated relevant tests
- [ ] ~updated relevant documentation~
- [ ] ~updated relevant milestone(s)~
- [ ] added relevant label(s)

2023-05-09 20:37 UTC, WilliamJamieson requested changes

2023-05-09 20:37 UTC, WilliamJamieson commented on tox.ini
> +    devdeps: scipy>=0.0.dev0
Same as all by previous comments, see https://github.com/spacetelescope/romancal/pull/695#discussion_r1189078751 and https://github.com/spacetelescope/romancal/pull/695/files/b791170675848ecb84fc1068587528c22403b284#r1189076034

2023-05-10 14:46 UTC, zacharyburnett commented
GitHub Actions are currently degraded; running `tox -e test-devdeps-xdist` locally results in the following `pip freeze`: 
```
astropy @ git+https://github.com/astropy/astropy@f2fbb112983e953fb772c5ac81ec50dfa34bcc19
coverage==7.2.5
execnet==1.9.0
iniconfig==2.0.0
numpy==1.25.0.dev0+1357.ga2d21d8ac
opencv-python-headless==4.7.0.72
packaging==23.1
pluggy==1.0.0
psutil==5.9.5
pyerfa==2.0.0.3
pytest==7.3.1
pytest-cov==4.0.0
pytest-doctestplus==0.12.1
pytest-xdist==3.2.1
PyYAML==6.0
scipy==1.11.0.dev0
stcal @ file:///Users/zburnett/projects/stcal/.tox/.tmp/package/19/stcal-1.3.8.dev5%2Bg4c16afc.tar.gz#sha256=5d7459096498f9e422408f887c55651c038dc0b432a00dda16c89d1ef70945bc
```

2023-05-11 11:50 UTC, kmacdonald-stsci approved these changes

2023-05-11 12:14 UTC, merged