JP-3463: Fix poisson variance calculation
spacetelescope/stcal pull request #255
Opened 2024-04-19 16:03 UTC by drlaw1558

This PR addresses the issue in JP-3463 where the addition of an average dark current to the poisson variance calculation step results in incorrect SCI array values for NIRSpec.  This PR adjusts the method of dealing with negative slopes and all-zero variance special cases.  Tested against two sets of MIRI data and one set of NIRSpec, and is working as intended both with and without specifying the new parameter.

**Checklist**

- [ ] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

2024-04-19 17:29 UTC, kmacdonald-stsci requested changes
Will you add a CI test to `test_ramp_fitting.py` for non-zero average dark current?

2024-04-19 19:06 UTC, drlaw1558 commented
> Will you add a CI test to `test_ramp_fitting.py` for non-zero average dark current?

I just added one; I haven't done much with pytest before though so let me know if you think it needs to be tweaked.

2024-04-20 16:47 UTC, kmacdonald-stsci commented
> > Will you add a CI test to `test_ramp_fitting.py` for non-zero average dark current?
> 
> I just added one; I haven't done much with pytest before though so let me know if you think it needs to be tweaked.

It looks fine.  Just something to test what the expected values should be, so it will fail if any changes are made to the way the dark current is used the test will fail.  I'll approve this PR now.

2024-04-20 16:48 UTC, kmacdonald-stsci approved these changes

2024-04-23 12:38 UTC, hbushouse reviewed
Just a minor comment on the change log entry. Will start a regression test run using this PR branch.

2024-04-23 12:49 UTC, hbushouse commented
Started regtest run at https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1404/

2024-04-23 15:11 UTC, drlaw1558 commented on CHANGES.rst
> +- Fix a bug in Poisson variance calculation visible when providing an average
Done

2024-04-23 16:40 UTC, hbushouse commented
Regression test results show what I'm guessing are expected differences in the SCI, ERR, and VAR_POISSON arrays in rate/rateints files, which then propagate to later products. So I think this looks OK.

2024-04-23 16:41 UTC, hbushouse approved these changes

2024-04-23 16:41 UTC, merged