JP-3677: Add maximum_shower_amplitude parameter to jump step
spacetelescope/stcal pull request #306
Opened 2024-10-15 21:48 UTC by drlaw1558

This PR addresses JP-3677 by adding a maximum_shower_amplitude parameter to the MIRI cosmic ray showers code, and ensuring that any changes in the rate image due to shower flagging are below this amplitude.

See also corresponding jwst PR XX

## Tasks
- [ ] update or add relevant tests
- [ ] update relevant docstrings and / or `docs/` page
- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] run regression tests with this branch installed (`"git+https://github.com/<fork>/stcal@<branch>"`)
    - [ ] [`jwst` regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) 
    - [ ] [`romancal` regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.apichange.rst``: change to public API
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
</details>

2024-10-15 21:53 UTC, drlaw1558 commented
Not sure why I can't request a review, but tagging @kmacdonald-stsci

2024-10-17 13:09 UTC, kmacdonald-stsci requested changes
There are portions of the code that are invoked unconditionally, but included in conditionals, which results in two parts of the code that need to be maintained, when there could be a single unconditional call to be maintained. 

Also, there are some formatting issues.

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
>          if find_showers:
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        tempdata[ingdq[intg,:,:,:] & donotuse_flag != 0] = np.nan
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        tempdata = indata[intg,:,:,:].copy()
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        tempdata[ingdq[intg,:,:,:] & donotuse_flag != 0] = np.nan
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        tempdata[gdq[intg,:,:,:] & donotuse_flag != 0] = np.nan
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        gdq[intg,:,indx[0],indx[1]] = ingdq[intg,:,indx[0],indx[1]]
Done

2024-10-17 20:14 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +        tempdata[gdq[intg,:,:,:] & donotuse_flag != 0] = np.nan
Done

2024-10-17 20:34 UTC, drlaw1558 commented on src/stcal/jump/jump.py
> +    for intg in range(nints):
Here the worry was that calling .copy() on the entire array could be extremely memory intensive for cases where there were a large number of integrations.  Looping over the integration is less efficient, but it looks like it still only takes 3 seconds even for an extreme TSO case with 257 ints, 30 groups, and 1024x1032 pixels.

2024-10-17 22:33 UTC, kmacdonald-stsci approved these changes
LGTM

2024-10-18 16:29 UTC, drlaw1558 commented
Updated to catch additional runtime warnings, and ensure the maximum amplitude is passed in the correct units so that it works for both FAST and SLOW mode data.

2024-11-08 22:02 UTC, drlaw1558 commented
Added one more minor change based on feedback from @mwregan2 to fix a prior bug with propagating flags to smoothed masks.

2024-11-18 17:11 UTC, tapastro requested changes
Change fragment needs renamed from 307 --> 306. Otherwise looks good, will approve pending fix.

2024-11-27 21:00 UTC, drlaw1558 commented
@tapastro Just double checked this for both MIRI MRS and Imaging detectors, and that change is fine.  Without running find_showers the reference pixels do not get flagged as DO_NOT_USE by the jump step, and so this change actually makes their treatment more consistent between whether or not the showers algorithm was run.

2024-12-02 22:36 UTC, schlafly approved these changes

2024-12-03 17:07 UTC, tapastro approved these changes

2024-12-03 17:07 UTC, merged